# Generated by Django 6.0.7 on 2026-07-22 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_cart', '0001_initial'),
        ('module_catalog', '0002_alter_category_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartReservationCooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooldown_until', models.DateTimeField(verbose_name='پایان کول\u200cداون')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_catalog.productvariant', verbose_name='تنوع محصول')),
            ],
            options={
                'verbose_name': 'کول\u200cداون رزرو سبد',
                'verbose_name_plural': 'کول\u200cداون\u200cهای رزرو سبد',
                'unique_together': {('user', 'variant')},
            },
        ),
    ]
