# Generated by Django 6.0.7 on 2026-07-19 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_accounts', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ماژول کاربر', 'verbose_name_plural': 'ماژول کاربران'},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید با 09 شروع شود و ۱۱ رقم باشد', regex='^09\\d{9}$')], verbose_name='شماره تلفن'),
        ),
    ]
