# Generated by Django 6.0.7 on 2026-07-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد پستی'),
        ),
    ]
