# Generated by Django 6.0.7 on 2026-07-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_orders', '0002_order_first_name_order_last_name_order_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(default=1, max_length=255, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(default=2, max_length=255, verbose_name='نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=255, verbose_name='کد پستی'),
        ),
    ]
